name: ML Pipeline with DVC, Training, and Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  hyperparameter-tuning-and-training:
    runs-on: ubuntu-latest

    steps:
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: echo $GDRIVE_CREDENTIALS_DATA > credentials_1.json
  
      - name: Modify DVC Remote
        run: dvc remote modify - local myremote credentialpath credentials_1.json
      - name: DVC Pull Data
        run: dvc pull -v
